name: CD Deploy

on:
  push: 

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Deploy application
        id: deployApplication
        run: |
          deploymentId=$( aws deploy create-deployment \
            --application-name cd-backend \
            --deployment-config-name CodeDeployDefault.OneAtATime \
            --deployment-group-name Jorge-DG \
            --github-location repository=jordonezp/arqui-cd,commitId=${{github.sha}} | jq -r '.deploymentId' )
            --description "Automatic deployment of ${{github.sha}}" \
          echo "deploymentId=$deploymentId" >> $GITHUB_OUTPUT
      # - name: Wait until deployment is done
      #   run: aws deploy wait deployment-successful --deployment-id ${{steps.deployApplication.outputs.deploymentId}}